---
on:
  pull_request:
    paths-ignore: &ignore-paths
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push:
    paths-ignore: *ignore-paths

name: Composer require checker

permissions:
  contents: read
  pull-requests: write

jobs:
  composer-require-checker:
    uses: yii2-framework/actions/.github/workflows/composer-require-checker.yml@v1
