---
on:
  pull_request:
    paths-ignore: &ignore-paths
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push:
    paths-ignore: *ignore-paths

name: ecs

permissions:
  contents: read
  pull-requests: write

jobs:
  easy-coding-standard:
    uses: yii2-framework/actions/.github/workflows/ecs.yml@v1
