---
on:
  pull_request:
    paths-ignore: &ignore-paths
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push:
    paths-ignore: *ignore-paths

name: mutation test

permissions:
  contents: read
  pull-requests: write

jobs:
  mutation:
    uses: yii2-framework/actions/.github/workflows/infection.yml@v1
    with:
      phpstan: true
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
